collections:
  api:
      output: true
  architecture:
      output: true
  lib:
      output: true
  tool:
      output: true
  h5:
    output: true
  skill:
    output: true
  experience:
    output: true